### ISSUE TITLE
Remove query param with empty value

### ISSUE THREAD

**Issue by SergGrey1992** [jschwindt/react-use-search-params-state#3]
const setValues = (newValues: Record<string, any>) => {
        const { [Object.keys(newValues)[0]]: remove, ...currentParams } =
            getAllCurrentParams(searchParams)
        if (newValues[Object.keys(newValues)[0]].length === 0) {
            setSearchParams({ ...currentParams })
        } else {
            setSearchParams({ ...currentParams, ...newValues })
        }
    }

**Comment by SergGrey1992** [comment]
I apologize for the previous answer it is not complete and does not take into account the deletion of multiple keys

here's an updated piece of code

`const setValues = (newValues: Record<string, any>) => {
        const currentParams = getAllCurrentParams(searchParams)
        for (const key in newValues) {
            if (Object.prototype.hasOwnProperty.call(newValues, key)) {
                const value = newValues[key]
                if (
                    value === '' ||
                    (Array.isArray(value) && value.length === 0)
                ) {
                    delete currentParams[key]
                    delete newValues[key]
                }
            }
        }
        setSearchParams({ ...currentParams, ...newValues })
    }
`

**Comment by jschwindt** [comment]
Hi @SergGrey1992! I added your code to delete empty params from the URL. Thanks!
